### ISSUE TITLE
디버그 패널 추가

### ISSUE THREAD

**Issue by juntz** [juntz/ZtmyCard#26]
현재 프로그램 설계상 멀티플레이가 아니면 게임이 정상적으로 동작하지 않기 때문에 샌드박스 모드( #20)를 추가하기 어렵고, 실제 게임 동작과 일치함을 보장할 수 없다.
대신 멀티플레이어 화면에 디버그 패널을 추가하여 다음과 같은 동작이 가능하도록 한다.
- [x] 임의의 카드를 선택한 필드에 추가
- [x] 크로노스를 임의의 시간으로 설정
- [x] 파워가 부족해도 카드를 사용 가능
- [x] 플레이어 체력을 변경
- [x] 기타 디버그에 유용하다고 생각되는 기능

**Comment by ffdd270** [comment]
Godot ImGui 붙여보는 건 어떨까요? 요구사항이 .NET 요구하는 Godot 버전으로 올라가긴 하지만 실시간 시각화에는 참 좋았답니다.

**Comment by juntz** [comment]
> Godot ImGui 붙여보는 건 어떨까요? 요구사항이 .NET 요구하는 Godot 버전으로 올라가긴 하지만 실시간 시각화에는 참 좋았답니다.

쓸수있는 도구가 있다면 써 봐야죠! 저는 적극 찬성입니다 :)
https://github.com/pkdawson/imgui-godot
고도에서 쓸 수 있는 플러그인도 있네요

**Comment by ffdd270** [comment]
<img width="1115" alt="image" src="https://github.com/user-attachments/assets/03901a81-b623-429b-b3eb-6fa650c19774">

이런 느낌으로 이번 주중부터 작업해놓겠습니다 'ㅁ 'b

**Comment by ffdd270** [comment]
<img width="593" alt="image" src="https://github.com/user-attachments/assets/26135cde-170f-42db-8d4a-edba674b5b76">

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/8bbd1c1d-e684-46f7-a13f-08802d537104">


중간 과정 공유해드립니다!
